version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - devops-network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro_alunos
    ports:
      - "3307:3306"
    networks:
      - devops-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - devops-network

networks:
  devops-network: