# Dockerfile para MariaDB
# Salve este arquivo como Dockerfile.mariadb na raiz do projeto

# Dockerfile (MariaDB)
FROM mariadb:10.5

# Defina as variáveis de ambiente para o banco de dados
ENV MYSQL_ROOT_PASSWORD=
ENV MYSQL_DATABASE=cadastro_alunos
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=

EXPOSE 3306
